# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

smith_waterman_mark_chars <- function(text, edit_mark) {
    .Call('_text_alignment_smith_waterman_mark_chars', PACKAGE = 'text.alignment', text, edit_mark)
}

lowercase <- function(data) {
    .Call('_text_alignment_lowercase', PACKAGE = 'text.alignment', data)
}

smith_waterman_matrix <- function(a, b, score_match, score_gap, score_mismatch, x) {
    .Call('_text_alignment_smith_waterman_matrix', PACKAGE = 'text.alignment', a, b, score_match, score_gap, score_mismatch, x)
}

smith_waterman_function <- function(a, b, score_gap, similarity) {
    .Call('_text_alignment_smith_waterman_function', PACKAGE = 'text.alignment', a, b, score_gap, similarity)
}

smith_waterman_path <- function(m, original_a, original_b, row_i, col_i, edit_mark) {
    .Call('_text_alignment_smith_waterman_path', PACKAGE = 'text.alignment', m, original_a, original_b, row_i, col_i, edit_mark)
}

smith_waterman_path_integer <- function(m, original_a, original_b, row_i, col_i, edit_mark) {
    .Call('_text_alignment_smith_waterman_path_integer', PACKAGE = 'text.alignment', m, original_a, original_b, row_i, col_i, edit_mark)
}

